# Generated by Django 3.2.9 on 2021-12-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20211202_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='wX5HYutVCV', max_length=1000),
        ),
    ]
