# Generated by Django 3.2.9 on 2021-12-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='HqKrFuJZEv', max_length=1000),
        ),
    ]
